#!/bin/python3

import math
import os
import random
import re
import sys


# Write your code here
operations= int(input())
stack=[]
maxer=-math.inf
for i in range(operations):
    temp=list(map(int,input().split()))
    if temp[0]==1:
        stack.append(temp[1])
        maxer=max(maxer, temp[1])
        if temp[1] > maxer:
            maxer = temp[1]
    elif temp[0]==2:
        k=stack.pop()
            
        if k >= maxer:
            if len(stack) is not 0:
                maxer = max(stack)
            else:
                maxer = -math.inf
    else:
        print(maxer)


